# Default values for upp-journal-log-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  stopTimeConfigmap: "journal-log-collector-stop-time"
log_collector:
  batchSize: 100
  workers: 8
  buffer: 256
  batchTimer: 5
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
image:
  repository: nexus.in.ft.com:5000/coco/log-collector
  pullPolicy: IfNotPresent
