# Default values for upp-journal-log-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  stopTimeConfigmap: "journal-log-collector-stop-time"
log_filter:
  image: coco/coco-logfilter:1.3.2
  memory: 256m
log_collector:
  image: coco/log-collector:1.0.0
  memory: 256m
  batchSize: 100
  workers: 8
  buffer: 256
  batchTimer: 5
image:
  repository: nexus.in.ft.com:5000/coco/log-collector
  pullPolicy: IfNotPresent
